# These are supported funding model platforms

github: [davidtdc3377]
patreon: davidtdc3377
ko_fi: davidtdc3377
liberapay: davidthedev
issuehunt: davidtdc3377/rblx-importer
custom: ['paypal.me/davidl24yt']
